import { MD3LightTheme, type MD3Theme } from 'react-native-paper';

export const brandColors = {
  forest: '#234437',
  forestSoft: '#46705C',
  lightMint: '#CFF5E7',
  mint: '#A8E6CF',
  outline: '#8ECFB5',
  softMint: '#B7F0D8',
  whisperMint: '#DFF8F0',
};

export const appTheme: MD3Theme = {
  ...MD3LightTheme,
  roundness: 6,
  colors: {
    ...MD3LightTheme.colors,
    primary: brandColors.mint,
    onPrimary: brandColors.forest,
    primaryContainer: brandColors.softMint,
    onPrimaryContainer: brandColors.forest,
    secondary: brandColors.softMint,
    onSecondary: brandColors.forest,
    secondaryContainer: brandColors.lightMint,
    onSecondaryContainer: brandColors.forest,
    tertiary: brandColors.lightMint,
    onTertiary: brandColors.forest,
    tertiaryContainer: brandColors.whisperMint,
    onTertiaryContainer: brandColors.forestSoft,
    error: '#BA4A4A',
    onError: '#FFFFFF',
    errorContainer: '#F9DDDD',
    onErrorContainer: '#7A2929',
    background: brandColors.whisperMint,
    onBackground: brandColors.forest,
    surface: '#F9FFFC',
    onSurface: brandColors.forest,
    surfaceVariant: brandColors.lightMint,
    onSurfaceVariant: brandColors.forestSoft,
    outline: brandColors.outline,
    outlineVariant: brandColors.lightMint,
    inverseSurface: brandColors.forest,
    inverseOnSurface: brandColors.whisperMint,
    inversePrimary: brandColors.lightMint,
    shadow: '#000000',
    scrim: '#000000',
    backdrop: 'rgba(35, 68, 55, 0.16)',
    surfaceDisabled: '#E6F5EE',
    onSurfaceDisabled: '#85A393',
    elevation: {
      level0: 'transparent',
      level1: '#F6FFF9',
      level2: '#F0FCF6',
      level3: '#EBF9F2',
      level4: '#E7F6EF',
      level5: '#E2F3EB',
    },
  },
};
